export const baseBlockWidth = 100;
export const baseBlockHeight = 30;
export const baseRunSpeed = 2000;
export const textPadding = 8;
export const stepActiveStyle = ["font-bold", "stroke-green-500"];
export const runningStyle = ["fill-green-100"];
export const selectedStyle = ["fill-cyan-100"];
export const errorStyle = ["fill-red-100"]
export const neutralStyle = ["fill-white", "hover:fill-cyan-50"];
export const canPlaceOnStyle = ["fill-green-50"];
export const cannotPlaceOnStyle = ["fill-white"]
export const errorBorder = ["border-2", "border-red-500"];
export const inactiveStyle = ["opacity-50"];