export const baseBlockWidth = 100;
export const baseBlockHeight = 30;
export const baseRunSpeed = 2000;
export const textPadding = 8;
export const stepActiveStyle = ["font-bold", "stroke-green-500"];
export const blockRunningStyle = ["fill-green-100"];
export const blockSelectedStyle = ["fill-cyan-100"];
export const blockErrorStyle = ["fill-red-100"]
export const blockNeutralStyle = ["fill-white", "hover:fill-cyan-50"];
export const blockCanPlaceOnStyle = ["fill-green-50"];
export const blockCannotPlaceOnStyle = ["fill-white"]
export const errorBorder = ["border-2", "border-red-500"];
export const inactiveStyle = ["opacity-50"];
export const speciSelectedStyle = ["bg-cyan-100"];
export const speciNeutralStyle = ["bg-white", "hover:bg-cyan-50"]